kafka-manager:
  ports:
  - 9000:9000/tcp
  image: sheepkiller/kafka-manager:1.3.1.6
  environment:
    - ZK_HOSTS=zk:2181
    - APPLICATION_SECRET=${app_secret}
    - KM_ARGS=${km_args}
  external_links:
    - ${zk_link}:zk
    - ${kafka_link}:kafka
  labels: 
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name